# Generated by Django 6.0.3 on 2026-05-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_subcategory_menuitem_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
